### ISSUE TITLE
Script stop when connect error

### ISSUE THREAD

**Issue by Daemonceltics** [chamli/CyberCrowl#9]
Traceback (most recent call last):
  File "cybercrowl.py", line 492, in <module>
    main()
  File "cybercrowl.py", line 475, in main
    crowl(list, url, args)
  File "cybercrowl.py", line 338, in crowl
    ress = requests.get(f_url, headers=headers ,allow_redirects=False, proxies=proxies, verify=False)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by tnmch** [comment]
Thanks , fixed !
